# NOTE: this is the production Docker Compose configuration file. DO NOT put
#       any stuff that must be available only in development. Please use the
#       file docker-compose.override.yml instead.
version: "2"
services:
  frontend:
    restart: always
    build: ./esco-translation-frontend
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
    links:
      - identifier:backend
    ports:
      - 4567:80
  identifier:
    image: semtech/mu-identifier:1.3.0
    links:
      - dispatcher:dispatcher          
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - login:login
      - importer:importer
      - hierarchyapi:hierarchyapi
      - kpisapi:kpisapi
      - dictionary:dictionary
      - validation:validation
      - indexer:indexer
      - cleanup:cleanup
      - export:export
    volumes:
      - ./config/dispatcher:/config

  scheduler:
    build: ./esco-core-scheduler
    links:
      - dispatcher:dispatcher
    volumes:
      - ./config/scheduler:/config
    environment:
      BASE_URL: "http://dispatcher"

  export:
    build: ./esco-translation-export
    links:
      - db:database
    volumes:
      - ./config/export:/config

  db:
    image: tenforce/virtuoso:1.3.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/virtuoso:/var/lib/virtuoso/db
    ports:
      - "9980:8890"

  solr:
    build: ./esco-core-solr
    volumes:
      - /data/solr_home
    command: mvn jetty:run -Dsolr.port=8080

  indexer:
    build: ./esco-core-delta-based-indexer
    ports:
      - "8891:8080"
    links:
      - solr:solr
      - db:database
    command: mvn spring-boot:run -D-Dsparql.namespace=http://mu.semte.ch/application -Dsparql.virtuoso.endpoint=http://database:8890/sparql/ -Dspring.data.solr.host=http://solr:8080/solr/collection1/ -Dqueues.enable=true

  resource:
    image: "semtech/mu-cache:0.5.0"
    links:
      - resourcebackend:backend
    environment:
      CACHE_BACKEND: "http://backend"
      SLOPPINESS_RATING: 1
      HTTP_MAX_HEADER_SIZE: 262144

  resourcebackend:
    image: semtech/mu-cl-resources:1.15.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    environment:
      BOOT: mu-cl-resources

  hierarchyapi:
    build: ./esco-core-hierarchy
    links:
      - db:database
    environment:
      HIER_CACHE_TIME: 0.01

  login:
    image: semtech/mu-login-service:2.7.0
    links:
      - db:database
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/application"
      MU_APPLICATION_SALT: "KteCAqj7bAjEavWhUhUHL4oPFc3ePvVVMKgHKoh7nTqAvhRuatxoTkpnePrLPiWk"

  importer:
    build: ./esco-translation-importer
    links:
      - db:database
    environment:
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/application"
      MU_GRAPH_STORE_ENDPOINT: "http://database:8890/sparql-graph-crud"

  kpisapi:
    build: ./esco-core-kpis
    links:
      - db:database

  dictionary:
    build: ./esco-translation-dictionary
    links:
      - db:database

  cleanup:
    build: ./esco-core-cleanup
    volumes:
      - "./config/cleanup:/config"
    links:
      - db:database

  validation:
    build: ./esco-core-validation
    links:
      - db:database
    environment:
      MU_SPARQL_TIMEOUT: "600"
    volumes:
      - "./config/validation:/config"
