(in-package :mu-cl-resources)

(setf *supply-cache-headers-p* t)
(setf *cache-model-properties-p* t)

(define-resource pillar ()
  :class (s-prefix "esco:ConceptScheme")
  :properties `((:preflabel :string-set ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://data.europa.eu/esco/concept-scheme/")
  :has-many `((concept :via ,(s-prefix "skos:topConceptOf")
                     :inverse t
                     :as "top-concepts")
              (structure :via ,(s-prefix "esco:structureFor")
                      :inverse t
                      :as "structures"))
  :on-path "taxonomies")

(define-resource concept-scheme ()
  :class (s-prefix "skos:ConceptScheme")
  :properties `((:preflabel :string-set ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description")))
  :resource-base (s-url "http://data.europa.eu/esco/concept-scheme/")
  :has-many `((concept :via ,(s-prefix "skos:topConceptOf")
                     :inverse t
                     :as "top-concepts")
             (concept :via ,(s-prefix "skos:inScheme")
                     :inverse t
                     :as "members"))
  :on-path "concept-schemes")

(define-resource structure ()
  :class (s-prefix "esco:Structure")
  :properties `((:name :string ,(s-prefix "skos:prefLabel"))
                (:description :string ,(s-prefix "dcterms:description"))
                (:coded-property :uri ,(s-prefix "esco:codedProperty"))
                (:default :string ,(s-prefix "esco:is-default-structure"))
                (:disabled :string ,(s-prefix "esco:is-disabled")))
  :has-one `((pillar :via ,(s-prefix "esco:structureFor")
                      :as "pillar")
            (concept-scheme :via ,(s-prefix "esco:codeList")
                      :as "code-list"))
  :resource-base (s-url "http://mu.semte.ch/vocabularies/hierarchy/")
  :on-path "structures")

(define-resource hierarchy ()
  :class (s-prefix "hier:Hierarchy")
  :properties `((:name :string ,(s-prefix "skos:prefLabel"))
                (:path :string ,(s-prefix "hier:path"))
                (:default :string ,(s-prefix "hier:default"))
                (:restriction :string ,(s-prefix "hier:restriction")))
  :resource-base (s-url "http://translation.escoportal.eu/hierarchies/")
  :on-path "hierarchies")

  (define-resource notification ()
    :class (s-prefix "mu:Notification")
    :properties `((:notification-type :string ,(s-prefix "mu:notificationType"))
                  (:purpose :string ,(s-prefix "mu:notificationPurpose"))
                  (:message :string ,(s-prefix "mu:notificationMessage"))
                  (:expiration-date :string ,(s-prefix "mu:notificationExpirationDate"))
                  (:list-button :string ,(s-prefix "mu:notificationListButton"))
                  (:list :string-set ,(s-prefix "mu:notificationList")))
    :resource-base (s-url "http://translation.escoportal.eu/notifications/")
    :on-path "notifications")

  (define-resource validation-result-collection ()
    :class (s-prefix "mu:validationResultCollection")
    :properties `((:timestamp :string ,(s-prefix "mu:timestamp"))
                  (:status :string ,(s-prefix "mu:status"))
                  (:rule-id :string ,(s-prefix "mu:ruleId"))
                  (:parameters :string-set ,(s-prefix "mu:parameters"))
                  (:types :string-set ,(s-prefix "mu:types")))
    :has-many `((validation-result :via ,(s-prefix "mu:hasResult")
                       :as "validation-results"))
    :resource-base (s-url "http://translation.escoportal.eu/validationResultCollection/")
    :on-path "validation-result-collections")

  (define-resource validation-result ()
    :class (s-prefix "mu:validationResult")
    :properties `((:parameter-uuid :string ,(s-prefix "mu:parameteruuid"))
                  (:parameter-language :string-set ,(s-prefix "mu:parameterlanguage"))
                  (:parameter-preflabel :string-set ,(s-prefix "mu:parameterpreflabel"))
                  (:parameter-label :string-set ,(s-prefix "mu:parameterlabel"))
                  (:parameter-labels :string-set ,(s-prefix "mu:parameterlabels"))
                  (:parameter-genders :string-set ,(s-prefix "mu:parametergenders"))
                  (:parameter-total :string-set ,(s-prefix "mu:parametertotal"))
                  (:parameter-literal-form :string-set ,(s-prefix "mu:parameterliteralForm"))
                  (:parameter-literal-forms :string-set ,(s-prefix "mu:parameterliteralForms"))
                  (:parameter-duplicate-in :string-set ,(s-prefix "mu:parameterduplicateIn"))
                  (:parameter-duplicate-type :string-set ,(s-prefix "mu:parameterduplicateType"))
                  (:timestamp :string ,(s-prefix "mu:timestamp"))
                  (:rule-id :string ,(s-prefix "mu:ruleId"))
                  (:parameter-type :string-set ,(s-prefix "mu:parametertype")))
    :has-one `((validation-result-collection :via ,(s-prefix "mu:hasResult")
                       :inverse t
                       :as "validation-result-collection"))
    :resource-base (s-url "http://translation.escoportal.eu/validationResult/")
    :on-path "validation-results")

(define-resource account ()
  :class (s-prefix "foaf:OnlineAccount")
  :properties `((:status :string ,(s-prefix "account:status")))
  :resource-base (s-url "http://translation.escoportal.eu/accounts/")
  :has-one `((user :via ,(s-prefix "foaf:account")
                   :inverse t
                   :as "user"))
  :on-path "accounts"
)

(define-resource user ()
  :class (s-prefix "foaf:Person")
  :properties `((:name :string ,(s-prefix "foaf:name"))
                (:language :string ,(s-prefix "dcterms:language"))
                (:disable-shortcuts :string ,(s-prefix "trans:disableShortcuts"))
                (:show-isco-in-chosen-language :string ,(s-prefix "trans:showIscoInChosenLanguage"))
				        (:role :string ,(s-prefix "trans:role")))
  :has-one `((poetry-task :via ,(s-prefix "trans:poetryTask")
                      :as "poetry-task"))
  :has-many `((account :via ,(s-prefix "foaf:account")
                      :as "accounts")
              (group :via ,(s-prefix "foaf:member")
              :inverse t
              :as "groups"))
  :resource-base (s-url "http://translation.escoportal.eu/users/")
  :on-path "users"
)

(define-resource group ()
  :class (s-prefix "trans:EcasGroup")
  :properties `((:name :string ,(s-prefix "foaf:name")))
  :has-many `((user :via ,(s-prefix "foaf:member")
              :as "members"))
  :resource-base (s-url "http://translation.escoportal.eu/groups/")
  :on-path "groups"
)

(define-resource concept-label ()
  :class (s-prefix "skosxl:Label")
  :properties `((:literal-form-values :language-string-set ,(s-prefix "skosxl:literalForm"))
                (:source :string ,(s-prefix "trans:source"))
                (:last-modified :string ,(s-prefix "esco:last-modified")))
  :resource-base (s-url "http://data.europa.eu/esco/label/")
  :features '(no-pagination-defaults)
  :has-many `((label-role :via ,(s-prefix "esco:hasLabelRole")
                    :as "roles")
			        (concept :via ,(s-prefix "skosxl:altLabel")
                    :inverse t
                    :as "alt-label-of")
              (concept :via ,(s-prefix "skosxl:hiddenLabel")
                    :inverse t
                    :as "hidden-label-of"))
	:has-one `((concept :via ,(s-prefix "skosxl:prefLabel")
					          :inverse t
                    :as "pref-label-of")
            (user :via ,(s-prefix "esco:last-modifier")
                    :as "last-modifier"))
  :on-path "concept-labels"
)

(define-resource label-role ()
  :class (s-prefix "esco:LabelRole")
  :properties `((:preflabel :string ,(s-prefix "skos:prefLabel")))
  :resource-base (s-url "http://translation.escoportal.eu/labelRole/")
  :features '(no-pagination-defaults)
  :on-path "label-roles"
  :has-many `((concept-label :via ,(s-prefix "esco:hasLabelRole")
              :inverse t
              :as "role-of"))
)

(define-resource task ()
	:class (s-prefix "trans:Task")
	:properties `((:language :string ,(s-prefix "trans:language"))
                (:status :string ,(s-prefix "trans:status"))
                (:last-modified :string ,(s-prefix "esco:last-modified")))
  :features '(no-pagination-defaults)
	:resource-base (s-url "http://translation.escoportal.eu/task/")
	:has-one `((poetry-task :via ,(s-prefix "trans:member")
              :inverse t
              :as "member-of")
					  (concept :via ,(s-prefix "trans:concept")
					    :as "concept")
            (user :via ,(s-prefix "esco:last-modifier")
              :as "last-modifier"))
	:on-path "tasks")

(define-resource poetry-task ()
  :class (s-prefix "trans:PoetryTask")
  :properties `((:status :string ,(s-prefix "trans:status"))
                (:poetryId :string ,(s-prefix "trans:poetryId")))
  :resource-base (s-url "http://translation.escoportal.eu/poetryTask/")
  :has-many `((task :via ,(s-prefix "trans:member")
                    :as "members"))
:on-path "poetry-tasks")

(define-resource concept ()
  :class (s-prefix "skos:Concept")
  :properties `((:nace :string ,(s-prefix "esco:hasNACECode"))
                (:codes :string-set ,(s-prefix "dcterms:identifier"))
                (:types :uri-set ,(s-prefix "rdf:type"))
                (:description :language-string-set ,(s-prefix "dcterms:description"))
                (:scope-note :language-string-set ,(s-prefix "skos:scopeNote"))
                (:esco-note :string ,(s-prefix "esco:note"))
                (:definition :language-string-set ,(s-prefix "skos:definition"))
                (:skill-type :uri-set ,(s-prefix "esco:skillType"))
                (:last-modified :string ,(s-prefix "esco:last-modified")))
  :resource-base (s-url "http://translation.escoportal.eu/topics/")
  :features '(no-pagination-defaults)
  :has-one `((user :via ,(s-prefix "esco:last-modifier")
                      :as "last-modifier"))
  :has-many `((concept-label :via ,(s-prefix "skosxl:altLabel")
                     :as "alt-labels")
			  (concept-label :via ,(s-prefix "skosxl:hiddenLabel")
                     :as "hidden-labels")
			  (concept-label :via ,(s-prefix "skosxl:prefLabel")
                     :as "pref-labels")
			  (concept :via ,(s-prefix "skos:broader")
                     :inverse t
                     :as "narrower")
        (concept :via ,(s-prefix "skos:broader")
                     :as "broader")
        (concept-relation :via ,(s-prefix "esco:isRelationshipFor")
                     :inverse t
                     :as "relations")
        (concept-relation :via ,(s-prefix "esco:refersConcept")
                     :inverse t
                     :as "inverse-relations")
			  (task :via ,(s-prefix "trans:concept")
                     :inverse t
                     :as "tasks")
			  (concept-scheme :via ,(s-prefix "skos:inScheme")
                     :as "taxonomy")
			  (concept-scheme :via ,(s-prefix "skos:topConceptOf")
                     :as "top-concept-of"))
  :on-path "concepts")

(define-resource concept-relation ()
  :class (s-prefix "esco:Relationship")
  :properties `((:type :uri-set ,(s-prefix "esco:hasRelationshipType")))
  :features '(no-pagination-defaults)
  :resource-base (s-url "http://translation.escoportal.eu/relations/")
  :has-one `((concept :via ,(s-prefix "esco:isRelationshipFor")
                    :as "from")
             (concept :via ,(s-prefix "esco:refersConcept")
                    :as "to"))
  :on-path "concept-relations")

(define-resource comment ()
  :class (s-prefix "esco:Comment")
  :properties `((:status :string ,(s-prefix "esco:status"))
                (:language :string ,(s-prefix "esco:language"))
                (:content :language-string-set ,(s-prefix "esco:content"))
                (:creation-date :string ,(s-prefix "esco:creation-date"))
                (:modification-date :string ,(s-prefix "esco:modification-date")))
  :resource-base (s-url "http://translation.escoportal.eu/comment/")
  :has-one `((concept :via ,(s-prefix "esco:isCommentFor")
            :as "about")
            (user :via ,(s-prefix "esco:isCommentBy")
            :as "author")
            (comment-notification :via ,(s-prefix "esco:notificationFor")
            :inverse t
            :as "notification"))
  :on-path "comments")

(define-resource comment-notification ()
  :class (s-prefix "esco:CommentNotification")
  :properties `((:status :string ,(s-prefix "esco:status"))
                (:created-when :string ,(s-prefix "esco:content"))
                (:solved :string ,(s-prefix "esco:solved"))
                (:solved-when :string ,(s-prefix "esco:solved-date")))
  :resource-base (s-url "http://translation.escoportal.eu/comment-notification/")
  :has-one `((user :via ,(s-prefix "esco:createdBy")
            :as "created-by")
            (user :via ,(s-prefix "esco:solvedBy")
            :as "solved-by")
            (comment :via ,(s-prefix "esco:notificationFor")
            :as "comment"))
  :has-many `((notification-assignment :via ,(s-prefix "esco:assignmentFor")
              :inverse t
              :as "assignments"))
  :on-path "comment-notifications")

(define-resource notification-assignment()
  :class (s-prefix "esco:NotificationAssignment")
  :properties `((:status :string ,(s-prefix "esco:status")))
  :resource-base (s-url "http://translation.escoportal.eu/notification-assignment/")
  :has-one `((user :via ,(s-prefix "esco:assignedTo")
            :as "assigned-to")
            (comment-notification :via ,(s-prefix "esco:assignmentFor")
            :as "notification"))
  :on-path "notification-assignments")
